### ISSUE TITLE
Make default protocol version configurable by profile

### ISSUE THREAD

**Issue by Razumain** [idsec-solutions/signservice-integration#40]
The current implementation sticks with version 1.1 of SignRequestExtension and SignResponseExtension unless the request contains more than one LoA identifier or contains an AuthnProfile element. In such cases the version 1.4 is used, but only if these conditions are met.

This made sense at the time when no or few sign services supported 1.4.

The current behaviour is still relevant if communicating with a legacy sign service, but it should be possible in a configuration profile (policy) to set the default version of this protocol i.e. to 1.4.

It is suggested that the capability to set a default protocol level is introduced in the configuration data implementation (defaulting to 1.4 if not set).

**Comment by martin-lindstrom** [comment]
Chapter 3.1 of [DSS Extension for Federated Central Signing Services](https://docs.swedenconnect.se/technical-framework/latest/09_-_DSS_Extension_for_Federated_Signing_Services.html#element-signrequestextension) states
that the default version is 1.1. So, I agree that we should make this configurable, but we have to use 1.1 as the default (unless features that require a higher version is used).
